/*
This is the configuration for the Keyball44 RGB Matrix bring-up keymap.
*/

#pragma once

#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 150
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR
#define RGB_MATRIX_DEFAULT_HUE 0
#define RGB_MATRIX_DEFAULT_SAT 255
#define RGB_MATRIX_DEFAULT_VAL RGB_MATRIX_MAXIMUM_BRIGHTNESS

#define TAP_CODE_DELAY 5

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define KEYBALL_AUTO_MOUSE_FORCE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 1
